# Generated by Django 4.1 on 2022-08-12 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='time',
        ),
        migrations.AddField(
            model_name='course',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='course',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Time'),
        ),
    ]
