# Generated by Django 4.1 on 2022-08-27 19:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0002_teacher_is_active'),
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='days_of_week',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], default=' ', max_length=63, verbose_name='Days of the week'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Number')),
                ('topic', models.CharField(max_length=100)),
                ('description', models.TextField(verbose_name='Description')),
                ('date', models.DateField(default=django.utils.datetime_safe.date.today, verbose_name='Date')),
                ('start_time', models.CharField(choices=[('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00')], max_length=9, verbose_name='Start time')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.comment')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Teacher.teacher')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
            },
        ),
    ]
