# Generated by Django 4.1 on 2022-08-12 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_course_time_course_end_time_course_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Start ime'),
        ),
    ]
