# Generated by Django 4.1 on 2022-08-12 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('surname', models.CharField(max_length=100, verbose_name='Surname')),
                ('age', models.PositiveSmallIntegerField(default=0, verbose_name='Age')),
                ('start_date', models.DateField(verbose_name='Start date of teaching')),
                ('group_count', models.PositiveSmallIntegerField(default=0, verbose_name='Number of groups')),
                ('course_name', models.CharField(max_length=150, verbose_name='Course name')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='Teachers/', verbose_name='Photo')),
                ('url', models.SlugField(default=None, max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'db_table': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=25, verbose_name='Телефон')),
                ('facebook', models.CharField(blank=True, max_length=50, null=True)),
                ('twitter', models.CharField(blank=True, max_length=50, null=True)),
                ('instagram', models.CharField(blank=True, max_length=50, null=True)),
                ('teacher', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.teacher')),
            ],
            options={
                'verbose_name': 'Профиль учителя',
                'verbose_name_plural': 'Профили учителей',
                'db_table': 'teacher_profile',
            },
        ),
    ]
