# Generated by Django 4.1 on 2022-08-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
