# Generated by Django 4.1 on 2022-08-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherprofile',
            options={},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(upload_to='Teachers/', verbose_name='Фото'),
        ),
        migrations.AlterModelTable(
            name='teacherprofile',
            table=None,
        ),
    ]
