# Generated by Django 4.1 on 2022-08-08 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0002_alter_teacherprofile_options_alter_teacher_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherprofile',
            options={'verbose_name': 'Профиль учителя', 'verbose_name_plural': 'Профили учителей'},
        ),
        migrations.AlterModelTable(
            name='teacherprofile',
            table='teacher_profile',
        ),
    ]
