# Generated by Django 4.1 on 2022-08-27 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_send_mail',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'An account with this email already exists, sign in with this email address'}, help_text='Enter email in format example@gmail.ru', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_email', message='Write correct email address', regex="^([A-Za-z0-9]{1}[-!#$%&'*+./=?^_`{}|~A-Za-z0-9]{,63})@([a-z]{1,}\\.){1,2}[a-z]{2,6}$")], verbose_name='email address'),
        ),
    ]
