# Generated by Django 4.1 on 2022-08-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SuperAdmin', 'SuperAdmin'), ('Administrator', 'Administrator'), ('Manager', 'Manager'), ('Teacher', 'Teacher')], max_length=15, null=True, verbose_name='Роль'),
        ),
    ]
