# Generated by Django 4.1 on 2022-08-30 19:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'The email has been already registered. Please, sign in using this email'}, help_text='Enter email in format example@gmail.ru', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_email', message='Invalid email', regex="^([A-Za-z0-9]{1}[-!#$%&'*+./=?^_`{}|~A-Za-z0-9]{1,63})@([A-za-z0-9-]{1,}\\.){1,2}[A-za-z0-9-]{2,6}$")], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Invalid name', regex='^([А-Яа-я0-9]{,50}$')], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Surname'),
        ),
    ]
