# Generated by Django 4.1 on 2022-08-30 20:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Invalid name', regex='^[А-Яа-я0-9]{,50}$')], verbose_name='Name'),
        ),
    ]
